// frontend/components/Footer.vue
<template>
  <footer class="bg-card border-t border-border mt-16">
    <div class="max-w-7xl mx-auto px-4 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
        <div>
          <div class="flex items-center gap-2 mb-4">
            <div class="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
              <span class="text-primary-foreground font-bold">AD</span>
            </div>
            <span class="font-bold text-lg text-primary">Adray ⴰⴷⵔⴰⵢ</span>
          </div>
          <p class="text-muted-foreground text-sm">Discover and register for amazing events.</p>
        </div>
        <div>
          <h3 class="font-semibold mb-3">Company</h3>
          <ul class="space-y-2 text-sm text-muted-foreground">
            <li><a href="#" class="hover:text-primary transition">About Us</a></li>
            <li><a href="#" class="hover:text-primary transition">Contact</a></li>
            <li><a href="#" class="hover:text-primary transition">Blog</a></li>
          </ul>
        </div>
        <div>
          <h3 class="font-semibold mb-3">Support</h3>
          <ul class="space-y-2 text-sm text-muted-foreground">
            <li><a href="#" class="hover:text-primary transition">Help Center</a></li>
            <li><a href="#" class="hover:text-primary transition">FAQs</a></li>
            <li><a href="#" class="hover:text-primary transition">Terms of Service</a></li>
          </ul>
        </div>
        <div>
          <h3 class="font-semibold mb-3">Connect</h3>
          <ul class="space-y-2 text-sm text-muted-foreground">
            <li><a href="#" class="hover:text-primary transition">Twitter</a></li>
            <li><a href="#" class="hover:text-primary transition">LinkedIn</a></li>
          </ul>
        </div>
      </div>
      <div class="border-t border-border pt-8 text-center text-sm text-muted-foreground">
        <p>&copy; {{ new Date().getFullYear() }} Adray ⴰⴷⵔⴰⵢ. All rights reserved.</p>
      </div>
    </div>
  </footer>
</template>
<script setup lang="ts">
</script>

// frontend/components/footer.tsx
// Footer component with links and company information
export function Footer() {
  return (
    <footer className="bg-card border-t border-border mt-16">
      <div className="max-w-7xl mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
          {/* Brand */}
          <div>
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
                <span className="text-primary-foreground font-bold">AD</span>
              </div>
              <span className="font-bold text-lg text-primary">Adray ⴰⴷⵔⴰⵢ</span>
            </div>
            <p className="text-muted-foreground text-sm">Discover and register for amazing events.</p>
          </div>

          {/* Company Links */}
          <div>
            <h3 className="font-semibold mb-3">Company</h3>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li>
                <a href="#" className="hover:text-primary transition">
                  About Us
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Contact
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Blog
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Careers
                </a>
              </li>
            </ul>
          </div>

          {/* Support Links */}
          <div>
            <h3 className="font-semibold mb-3">Support</h3>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li>
                <a href="#" className="hover:text-primary transition">
                  Help Center
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Terms of Service
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Privacy Policy
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  FAQ
                </a>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h3 className="font-semibold mb-3">Legal</h3>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li>
                <a href="#" className="hover:text-primary transition">
                  Terms
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Privacy
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Cookies
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-primary transition">
                  Security
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div className="border-t border-border pt-8 flex flex-col md:flex-row justify-between items-center text-sm text-muted-foreground">
          <p>&copy; 2025 Adray ⴰⴷⵔⴰⵢ. All rights reserved.</p>
          <div className="flex gap-4 mt-4 md:mt-0">
            <a href="#" className="hover:text-primary transition">
              Twitter
            </a>
            <a href="#" className="hover:text-primary transition">
              LinkedIn
            </a>
            <a href="#" className="hover:text-primary transition">
              Facebook
            </a>
          </div>
        </div>
      </div>
    </footer>
  )
}
