// frontend/app/events/page.tsx
// Events browse page with filtering and search
"use client"

import { useState } from "react"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { EventCard } from "@/components/event-card"
import { useEvents } from "@/lib/hooks/use-events"
import { Button } from "@/components/ui/button"

export default function EventsPage() {
  const [filters, setFilters] = useState({
    city: "",
    category: "",
    search: "",
  })

  const { events, isLoading, error } = useEvents(filters)

  const categories = ["Technology", "Design", "Business", "Education", "Entertainment"]
  const cities = ["New York", "San Francisco", "Austin", "Chicago", "Los Angeles"]

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar isLoggedIn={false} />

      <main className="flex-grow max-w-7xl mx-auto w-full px-4 py-12">
        <h1 className="text-4xl font-bold mb-8">Browse Events</h1>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          {/* Filters Sidebar */}
          <div className="lg:col-span-1">
            <div className="bg-card border border-border rounded-lg p-6 sticky top-24">
              <h3 className="font-bold text-lg mb-4">Filters</h3>

              {/* Search */}
              <div className="mb-6">
                <label className="block text-sm font-medium mb-2">Search</label>
                <input
                  type="text"
                  placeholder="Event name..."
                  value={filters.search}
                  onChange={(e) => setFilters({ ...filters, search: e.target.value })}
                  className="w-full px-3 py-2 rounded border border-border bg-input focus:outline-none focus:ring-2 focus:ring-primary text-sm"
                />
              </div>

              {/* Category Filter */}
              <div className="mb-6">
                <label className="block text-sm font-medium mb-3">Category</label>
                <div className="space-y-2">
                  {categories.map((cat) => (
                    <label key={cat} className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={filters.category === cat}
                        onChange={() => setFilters({ ...filters, category: filters.category === cat ? "" : cat })}
                        className="w-4 h-4 rounded border-border"
                      />
                      <span className="text-sm">{cat}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* City Filter */}
              <div className="mb-6">
                <label className="block text-sm font-medium mb-3">City</label>
                <div className="space-y-2">
                  {cities.map((city) => (
                    <label key={city} className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={filters.city === city}
                        onChange={() => setFilters({ ...filters, city: filters.city === city ? "" : city })}
                        className="w-4 h-4 rounded border-border"
                      />
                      <span className="text-sm">{city}</span>
                    </label>
                  ))}
                </div>
              </div>

              <Button
                variant="outline"
                className="w-full bg-transparent"
                onClick={() => setFilters({ city: "", category: "", search: "" })}
              >
                Clear Filters
              </Button>
            </div>
          </div>

          {/* Events Grid */}
          <div className="lg:col-span-3">
            {isLoading ? (
              <div className="flex justify-center py-12">
                <div className="text-center">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
                  <p className="text-muted-foreground">Loading events...</p>
                </div>
              </div>
            ) : events.length === 0 ? (
              <div className="text-center py-12">
                <p className="text-muted-foreground mb-4">No events found matching your criteria</p>
                <Button variant="outline" onClick={() => setFilters({ city: "", category: "", search: "" })}>
                  Clear Filters
                </Button>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {events.map((event) => (
                  <EventCard key={event.id} {...event} />
                ))}
              </div>
            )}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}

// frontend/pages/events.vue
<template>
  <div>
    <div class="max-w-7xl mx-auto px-4 py-8">
      <h1 class="text-4xl font-bold mb-8">Browse Events</h1>

      <!-- Filters -->
      <div class="bg-card border border-border rounded-lg p-6 mb-8">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label class="block text-sm font-medium mb-2">Search</label>
            <input
              v-model="filters.search"
              type="text"
              placeholder="Search events..."
              class="w-full px-4 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
            />
          </div>
          <div>
            <label class="block text-sm font-medium mb-2">City</label>
            <select
              v-model="filters.city"
              class="w-full px-4 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="">All Cities</option>
              <option v-for="city in cities" :key="city" :value="city">{{ city }}</option>
            </select>
          </div>
          <div>
            <label class="block text-sm font-medium mb-2">Category</label>
            <select
              v-model="filters.category"
              class="w-full px-4 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="">All Categories</option>
              <option v-for="category in categories" :key="category" :value="category">{{ category }}</option>
            </select>
          </div>
        </div>
      </div>

      <!-- Events Grid -->
      <div v-if="isLoading" class="text-center py-12">
        <p class="text-muted-foreground">Loading events...</p>
      </div>

      <div v-else-if="error" class="text-center py-12">
        <p class="text-destructive">Error loading events: {{ error }}</p>
      </div>

      <div v-else-if="events.length === 0" class="text-center py-12">
        <p class="text-muted-foreground">No events found. Try adjusting your filters.</p>
      </div>

      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <EventCard
          v-for="event in events"
          :key="event.id"
          :id="event.id"
          :title="event.title"
          :description="event.description"
          :date="event.date"
          :city="event.city"
          :remaining-seats="event.remainingSeats"
          :total-seats="event.totalSeats"
          :image-url="event.imageUrl"
          :category="event.category"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const filters = ref({
  city: '',
  category: '',
  search: '',
})

const categories = ['Technology', 'Design', 'Business', 'Education', 'Entertainment']
const cities = ['New York', 'San Francisco', 'Austin', 'Chicago', 'Los Angeles']

const { events, isLoading, error } = useEvents(filters)
</script>
