// frontend/app/login/page.tsx
// Login page with email and password form
"use client"

import type React from "react"

import { useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { useAuth } from "@/lib/hooks/use-auth"

export default function LoginPage() {
  const router = useRouter()
  const { login, loading, error } = useAuth()
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [formError, setFormError] = useState("")

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setFormError("")

    if (!email || !password) {
      setFormError("Please fill in all fields")
      return
    }

    try {
      await login(email, password)
      router.push("/dashboard")
    } catch (err) {
      setFormError(error || "Login failed")
    }
  }

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar isLoggedIn={false} />

      <main className="flex-grow max-w-md mx-auto w-full px-4 py-12">
        <div className="bg-card rounded-lg border border-border shadow-sm p-8">
          <h1 className="text-3xl font-bold mb-2">Welcome Back</h1>
          <p className="text-muted-foreground mb-6">Sign in to your EventHub account</p>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Error Message */}
            {formError && (
              <div className="p-3 bg-destructive/10 border border-destructive/20 rounded text-destructive text-sm">
                {formError}
              </div>
            )}

            {/* Email Input */}
            <div>
              <label className="block text-sm font-medium mb-2">Email</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="you@example.com"
                className="w-full px-4 py-2 rounded-lg border border-border bg-input focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>

            {/* Password Input */}
            <div>
              <label className="block text-sm font-medium mb-2">Password</label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Enter your password"
                className="w-full px-4 py-2 rounded-lg border border-border bg-input focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>

            {/* Submit Button */}
            <Button type="submit" disabled={loading} className="w-full bg-primary hover:bg-primary/90 py-2">
              {loading ? "Signing in..." : "Sign In"}
            </Button>
          </form>

          {/* Sign Up Link */}
          <p className="text-center mt-6 text-muted-foreground">
            Don't have an account?{" "}
            <Link href="/signup" className="text-primary font-medium hover:underline">
              Sign Up
            </Link>
          </p>
        </div>
      </main>

      <Footer />
    </div>
  )
}

// frontend/pages/login.vue
<template>
  <div class="max-w-md mx-auto px-4 py-16">
    <h1 class="text-3xl font-bold mb-8 text-center">Login</h1>
    
    <form @submit.prevent="handleSubmit" class="space-y-6 bg-card border border-border rounded-lg p-8">
      <div v-if="formError" class="bg-destructive/10 text-destructive px-4 py-3 rounded-md text-sm">
        {{ formError }}
      </div>

      <div>
        <label class="block text-sm font-medium mb-2">Email</label>
        <input
          v-model="email"
          type="email"
          required
          class="w-full px-4 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
          placeholder="your@email.com"
        />
      </div>

      <div>
        <label class="block text-sm font-medium mb-2">Password</label>
        <input
          v-model="password"
          type="password"
          required
          class="w-full px-4 py-2 border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
          placeholder="••••••••"
        />
      </div>

      <button
        type="submit"
        :disabled="loading"
        class="w-full px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 transition disabled:opacity-50"
      >
        {{ loading ? 'Logging in...' : 'Login' }}
      </button>

      <div class="text-center text-sm text-muted-foreground">
        Don't have an account?
        <NuxtLink to="/signup" class="text-primary hover:underline">Sign up</NuxtLink>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
const router = useRouter()
const { login, loading } = useAuth()
const email = ref('')
const password = ref('')
const formError = ref('')

const handleSubmit = async () => {
  formError.value = ''
  if (!email.value || !password.value) {
    formError.value = 'Please fill in all fields'
    return
  }
  try {
    await login(email.value, password.value)
    router.push('/')
  } catch (err) {
    formError.value = 'Login failed. Please try again.'
  }
}
</script>
